services:
  frontend:
    build: ./frontend
    ports:
      - "5000:80"
    depends_on:
      - backend
    env_file:
      - .env
    # restart: always

  backend:
    build: ./backend
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - .env
    # restart: always

  db:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # restart: always

volumes:
  postgres_data:
